## Basic Numpy Operations

### Slicing and Filtering

In [1]:
import numpy as np

In [12]:
np.random.seed(42)
jan_coffee_sales = np.random.randint(25, 200, size=(4, 7)) # size corresponds to 7 days in 4 weeks of the month
print(jan_coffee_sales)

[[127 117  39 131  96  45 127]
 [146  99 112 141 124 128 176]
 [155 174  77  26 112 182  62]
 [154  45 185  82  46 113  73]]


Slice the array

In [15]:
monday_sales = jan_coffee_sales[:, 1]
print(monday_sales)

[117  99 174  45]


The long way to filter an array

In [3]:
np.array([n for n in np.random.randint(1, 10, 100) if n % 2 == 0])

array([2, 8, 4, 4, 4, 8, 6, 2, 6, 8, 4, 8, 8, 8, 2, 4, 8, 2, 2, 2, 4, 8, 8,
       2, 4, 6, 8, 6, 6, 4, 2, 6, 2, 2, 4, 8, 8, 8, 4])

A new and shorter way to filter an array only possible by using numpy

In [5]:
random_array = np.random.randint(1, 10, 100)
random_array[random_array % 2 == 0]

array([8, 2, 6, 2, 2, 8, 4, 4, 4, 8, 2, 6, 6, 6, 6, 8, 4, 8, 6, 8, 4, 4, 6,
       2, 2, 2, 2, 8, 4, 6, 4, 6, 4, 6, 4, 2, 4, 4, 4, 2, 6, 8, 6, 6, 8, 6,
       6, 8, 6, 4, 8, 4])

Conditional filtering

In [7]:
random_array % 2 == 0  # Boolean slicing and filtering

array([False, False,  True, False, False,  True, False, False,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
       False, False,  True, False, False,  True,  True,  True, False,
        True, False,  True,  True, False,  True,  True, False, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False, False, False, False,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True, False, False,
       False,  True,  True, False, False,  True, False,  True, False,
       False,  True, False,  True, False, False,  True,  True, False,
       False, False, False, False,  True,  True,  True, False,  True, False], dtype=bool)